### ISSUE TITLE
@tjvr feature-request: comments

### ISSUE THREAD

**Issue by peey** [andres-arana/vim-nearley#2]
Hey, I'm opening this issue in this repo because the [fork](https://github.com/tjvr/vim-nearley) doesn't have an issues section. So it's meant for @tjvr and not the owner of this repo

The syntax plugin works perfectly except nearley comments which start with a hash. Can this be added?

**Comment by tjvr** [comment]
If you can figure out how to do it, I’ll gladly accept a PR :-)

**Comment by tjvr** [comment]
Wait, but comments should already work?

**Comment by peey** [comment]
This is what I'm seeing:

![image](https://user-images.githubusercontent.com/4688870/34338236-a60ea924-e98c-11e7-8ab2-aa699aae0191.png)

**Comment by peey** [comment]
The text in the screenshot to help reproduce the error

```
@{%
const moo = require("moo")
// a js comment
%}

Program -> _ Body _ {% ([,body,]) => ({type:"Program", body: body}) %}

# a non-js comment : Program -> _ Body _ {% (x) => x%}

```

**Comment by tjvr** [comment]
They work for me! Maybe you're using an outdated version of Vim, or an unusual colorscheme? :)

**Comment by peey** [comment]
I'm using 7.4. If you can't reproduce the issue then it's probably local to me, I'll try to update
